#!/usr/bin/env python

import json
import sys
import datetime

def today_str():
    return datetime.date.strftime(datetime.date.today(), "%Y-%m-%d")

title = input("title: ")
author = input("author: ")
date = input("date (%s): " % today_str())

if (title and author):
    if (not date):
        date = today_str()
    entry = { 'title': title, 'author': author, 'date': date }
    with open("static/books.json", "r+", encoding="utf-8") as f:
        js = json.load(f)
        js.insert(0, entry)
        s = json.dumps(js, indent=4, sort_keys=True,
                separators=(',', ': '), ensure_ascii=False)
        f.seek(0)
        f.truncate()
        f.write(s)
